### ISSUE TITLE
what type are you used?

### ISSUE THREAD

**Issue by tuteming** [malashinroman/CSVA#4]
in project, figure Registration under season changes (left), registration map against photo (right)
what type are you used?

thanks.

**Comment by Nuzhny007** [comment]
Hi!
Type = 212
https://github.com/malashinroman/CSVA/blob/master/examples/match_aero/aerospace_demo.cpp#L202

**Comment by tuteming** [comment]
thanks

**Comment by tuteming** [comment]
in project, example : registration map against photo
I use my data can not obtain correct result.
If it is possible, can you offer this example data for test.

thanks

**Comment by malashinroman** [comment]
Hi, sorry for a delay with reply. Photo against map is challenging and it doesn't work always, especially in low textured images. Unfortunately I don't have the example images at my hand. 

My advice will be to try  equalizing scale of map and image using prior knowledge (which is usually possible). Though key points based methods are "scale invariant", equal scales help to build more similar descriptions with larger match clusters.

Hope that helps

**Comment by tuteming** [comment]
Thanks 從我的iPhone傳送malashinroman ***@***.***> 於 2024年4月2日 下午4:11 寫道：﻿
Hi, sorry for a delay with reply. Photo against map is challenging and it doesn't work always, especially in low textured images. Unfortunately I don't have the example images at my hand.
My advice will be to try matching equalizing scale a priori (which is usually possible). Though key points based methods are "scale invariant", equal scales help to build more similar descriptions with larger match clusters.
Hope that helps

**Comment by tuteming** [comment]
by examples/match_aero/aerospace_demo.cpp,
how to implement  "Registration under season changes (left)" in project, example.
thanks

**Comment by malashinroman** [comment]
> by examples/match_aero/aerospace_demo.cpp, how to implement "Registration under season changes (left)" in project, example. thanks

You can just apply CSVA in 212 regime as suggested by @Nuzhny007. Then you have a transformation matrix that maps images to the same coordinate system. Transform image 2 with the use of the transform. For visualization I showed 20 lines of image 1 after 20 lines of image 2 after 20 lines of image 1, and so on.
